### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by anuejn** [apertus-open-source-cinema/nmigen-gateware#4]
This Repository needs a license. I would vote fro AGPL-3.0.
Is that okay for you @rroohhh @ekliptik ?

**Comment by rroohhh** [comment]
Ok for me

**Comment by mithro** [comment]
Please don't use AGPL. [Using AGPL means I will never be able to contribute or look at this repository while working at my current employer](https://opensource.google/docs/using/agpl-policy/).

While my employer's preference is Apache 2.0, using GPL is perfectly fine if you want a "share and share alike" license. I'm also *personally* supportive of using GPL (but not AGPL) licenses.

**Comment by ekliptik** [comment]
Honestly, the advantage of Affero seems to be irrelevant for a HDL setup. Considering this would exclude mithro from participating in development, I'm for downgrading to GPL v3

**Comment by rroohhh** [comment]
GPL-3+ is fine for me aswell

**Comment by anuejn** [comment]
> Please don't use AGPL. Using AGPL means I will never be able to contribute or look at this repository while working at my current employer.

Well to me that comes without too much surprise for a company that makes money by selling proprietary software-over-the network ;).

However I am fine with GPL-3+ as well :+1:

**Comment by anuejn** [comment]
closed in #5
